### PR TITLE
Add cases for lazy IEnumerable

### PR DESCRIPTION
**Pull request by darren-clark**

### CODE REVIEW

**Comment by m-jovanovic** [comment]
It would probably be a better idea to create a separate benchmark with this approach so that we can compare both of them.

**Comment by darren-clark** [comment]
Yeah, that occurred to me right after I pushed this. Updated with new cases.
Foreach/any/all are slightly slower than collection, as one would expect.
Distinct/HashSet are almost 3x slower, as one would expect.

Good to remind people about not enumerating multiple times. ;)

**Comment by m-jovanovic** [comment]
Are you also up for running the entire benchmark and adding the results in the README?

I do believe we can format it as a table using Markdown.

**Comment by darren-clark** [comment]
Sure. Already ran it and had the MD output from the results. Just pasted it into Readme.

**Pull request merged**
